In [2]:
import pandas as pd

path = "steam_game_reviews.csv"
data = pd.read_csv(path, dtype=object)
data

,review,hours_played,helpful,funny,recommendation,date,game_name,username
0,The game itself is also super fun. The PvP and...,39.9,"1,152",13,Recommended,14 September,"Warhammer 40,000: Space Marine 2",Sentinowl\n224 products in account
1,Never cared much about Warhammer until this ga...,91.5,712,116,Recommended,13 September,"Warhammer 40,000: Space Marine 2",userpig\n248 products in account
2,A salute to all the fallen battle brothers who...,43.3,492,33,Recommended,14 September,"Warhammer 40,000: Space Marine 2",Imparat0r\n112 products in account
3,this game feels like it was made in the mid 20...,16.8,661,15,Recommended,14 September,"Warhammer 40,000: Space Marine 2",Fattest_falcon
4,Reminds me of something I've lost. A genuine g...,24.0,557,4,Recommended,12 September,"Warhammer 40,000: Space Marine 2",Jek\n410 products in account
...,...,...,...,...,...,...,...,...
992148,2022 Early Access Review Loads of fun!Initiall...,4.2,1,0,Recommended,"August 4, 2022",Turbo Golf Racing,"Fatal Exit\n1,902 products in account"
992149,2022 Early Access Review Great fun!,8.5,1,0,Recommended,"August 4, 2022",Turbo Golf Racing,cleybaR
992150,2022 Early Access Review Excellent pick up and...,83.3,2,0,Recommended,"August 4, 2022",Turbo Golf Racing,Sim\n600 products in account
992151,2022 Early Access Review This game is so much ...,3.8,1,0,Recommended,"August 4, 2022",Turbo Golf Racing,Fatboybadboy
992152,2022 Early Access Review Im in love with the G...,315.3,0,0,Not Recommended,"August 4, 2022",Turbo Golf Racing,Wolfy\n136 products in account

In [3]:
data.head(1)

,review,hours_played,helpful,funny,recommendation,date,game_name,username
0,The game itself is also super fun. The PvP and...,39.9,"1,152",13,Recommended,14 September,"Warhammer 40,000: Space Marine 2",Sentinowl\n224 products in account

In [4]:
data.tail(1)

,review,hours_played,helpful,funny,recommendation,date,game_name,username
992152,2022 Early Access Review Im in love with the G...,315.3,0,0,Not Recommended,"August 4, 2022",Turbo Golf Racing,Wolfy\n136 products in account

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992153 entries, 0 to 992152
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   review          991650 non-null  object
 1   hours_played    992153 non-null  object
 2   helpful         992153 non-null  object
 3   funny           992153 non-null  object
 4   recommendation  992153 non-null  object
 5   date            992153 non-null  object
 6   game_name       992153 non-null  object
 7   username        992072 non-null  object
dtypes: object(8)
memory usage: 60.6+ MB

In [6]:
# Определите, зависят ли характеристики `hours_played` и `recommendation` 
# друг от друга в игре Subnautica.


df_sub = data[data["game_name"] == "Subnautica"].copy() 
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4980 entries, 298031 to 303010
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review          4980 non-null   object
 1   hours_played    4980 non-null   object
 2   helpful         4980 non-null   object
 3   funny           4980 non-null   object
 4   recommendation  4980 non-null   object
 5   date            4980 non-null   object
 6   game_name       4980 non-null   object
 7   username        4980 non-null   object
dtypes: object(8)
memory usage: 350.2+ KB

In [7]:
df_sub["recommendation"].value_counts()

recommendation
Recommended        4917
Not Recommended      63
Name: count, dtype: int64

In [8]:
df_sub["recommendation"] = df_sub["recommendation"].apply(
    lambda x: 1 if x == "Recommended" else 0
)
df_sub.head(1)

,review,hours_played,helpful,funny,recommendation,date,game_name,username
298031,2018 Early Access Review It's hard to overstat...,92.9,"2,440",60,1,"1 January, 2018",Subnautica,Blaine\n441 products in account

In [9]:
df_sub["recommendation"].value_counts()

recommendation
1    4917
0      63
Name: count, dtype: int64

In [10]:
df_sub["recommendation"].corr(df_sub["hours_played"])

ValueError: could not convert string to float: '1,077.7'

In [ ]:
df_sub["hours_played"] = df_sub["hours_played"].str.replace(",", "").astype(float)

In [ ]:
df_sub["hours_played"]

298031     92.9
298032     30.5
298033    433.3
298034    204.9
298035     30.4
          ...
303006     90.0
303007     46.4
303008    212.5
303009     26.3
303010    126.1
Name: hours_played, Length: 4980, dtype: float64

In [ ]:
df_sub["recommendation"].corr(df_sub["hours_played"])

np.float64(0.010075444866241137)

In [ ]:
nefative_max = df_sub[df_sub["recommendation"] == 0]["hours_played"].max()
nefative_max

np.float64(397.4)

In [ ]:
positive_min = df_sub[df_sub["recommendation"] == 1]["hours_played"].min()
positive_min

np.float64(0.2)

In [ ]:
# Используя данные из файла `steam_game_reviews.csv`, 
# найдите среднее число дней, прошедших со дня публикации отзывов для
# игры Subnautica.

In [11]:
df_sub.head(1)

,review,hours_played,helpful,funny,recommendation,date,game_name,username
298031,2018 Early Access Review It's hard to overstat...,92.9,"2,440",60,1,"1 January, 2018",Subnautica,Blaine\n441 products in account

In [12]:
df_sub["date"]

298031       1 January, 2018
298032     23 December, 2020
298033    24 September, 2023
298034        23 April, 2022
298035      14 January, 2019
                 ...
303006      January 19, 2019
303007       January 9, 2019
303008     November 24, 2018
303009     November 25, 2018
303010     November 22, 2018
Name: date, Length: 4980, dtype: object

In [13]:
df_sub["date"] = pd.to_datetime(df_sub["date"], format="mixed", errors="coerce")

In [14]:
df_sub["date"]

298031   2018-01-01
298032   2020-12-23
298033   2023-09-24
298034   2022-04-23
298035   2019-01-14
            ...
303006   2019-01-19
303007   2019-01-09
303008   2018-11-24
303009   2018-11-25
303010   2018-11-22
Name: date, Length: 4980, dtype: datetime64[ns]

In [15]:
df_sub["date"].isna().sum()

np.int64(198)

In [ ]:
df_sub = df_sub.dropna(subset="date")
df_sub

In [20]:
today = pd.Timestamp.now().date()
today

datetime.date(2026, 10, 27)

In [23]:
df_sub["count_days"] = (pd.to_datetime(today) - df_sub["date"]).dt.days
df_sub["count_days"]

C:\Users\Legionchik\AppData\Local\Temp\ipykernel_27984\702826187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["count_days"] = (pd.to_datetime(today) - df_sub["date"]).dt.days

298031    3221
298032    2134
298033    1129
298034    1648
298035    2843
          ...
303006    2838
303007    2848
303008    2894
303009    2893
303010    2896
Name: count_days, Length: 4782, dtype: int64

In [ ]:
df_sub.sort_values(by="count_days", ascending=False)

In [28]:
df_sub["count_days"].mean()

np.float64(2847.9205353408615)